name: Build Image (Fork)
on:
  push:
    paths-ignore:
      - Dockerfile.base
      - README.md
    branches:
      - master
      - develop
  schedule:
    - cron:  '59 23 * * *'

jobs:

  ubuntu_bionic_deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Copy Repo Files
      uses: actions/checkout@v3
 
    - name: Set up Docker Buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
        buildx-version: latest
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Copy Dockerfile
      run: cp Dockerfile Dockerfile.ubuntu-hirsute; sed -i.bak "s/FROM.*/FROM ${ORG}\/github-runner-base:ubuntu-21.04/" Dockerfile.ubuntu-hirsute
    - name: Log in to GitHub Docker Registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: docker.pkg.github.com
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      uses: nick-invision/retry@v2
      with:
        max_attempts: 3
        retry_on: error
        timeout_minutes: 120
        command: docker buildx build -f Dockerfile.ubuntu-hirsute -t ${{ github.repository }:ubuntu-hirsute --output "type=image,push=true" --platform linux/amd64,linux/arm/v7,linux/arm64 .
